modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"

[[mods]]
modId="itemphysic"
version="1.6.2"
displayName="ItemPhysic"
authors="CreativeMD"
description="Realistic item physics"
